# Generated by Django 5.0.1 on 2024-01-26 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dekho_app', '0003_showroomlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='showrooms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_dekho_app.showroomlist'),
        ),
    ]
