# Generated by Django 5.0.1 on 2024-01-31 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dekho_app', '0004_carlist_showrooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carlist',
            old_name='showrooms',
            new_name='cars',
        ),
    ]
