# Generated by Django 5.0.1 on 2024-01-31 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dekho_app', '0005_rename_showrooms_carlist_cars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carlist',
            old_name='cars',
            new_name='showrooms',
        ),
    ]
